# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for the NLapt GUI (packaging reserve).

Build with (from the repository root)::

    python -m PyInstaller packaging/nlapt.spec --noconfirm

Produces an onedir, windowed (no console) build named ``NLapt`` under
``dist/NLapt``. The exe/window icon is ``packaging/icon.ico`` (generated by
``packaging/make_icon.py``; replace that file to swap the icon).

PyInstaller injects ``Analysis`` / ``PYZ`` / ``EXE`` / ``COLLECT`` into the
spec's namespace at build time; this file only needs to be valid Python.
"""

import os
import sys

from PyInstaller.utils.hooks import collect_submodules

APP_NAME = "NLapt"
# Relative paths in a spec resolve against the spec's own directory
# (packaging/), NOT the invocation cwd — so anchor everything on SPECPATH
# (injected by PyInstaller: the directory containing this file).
ROOT = os.path.dirname(SPECPATH)  # noqa: F821 - injected by PyInstaller
ENTRY_SCRIPT = os.path.join(ROOT, "nlapt_gui", "__main__.py")
ICON_FILE = os.path.join(ROOT, "packaging", "icon.ico")

# collect_submodules imports the packages, so the repo root must be importable
# regardless of where PyInstaller was invoked from.
sys.path.insert(0, ROOT)

# The codebase uses string-based lazy imports that static analysis cannot see:
# PEP 562 __getattr__ exports (nlapt/__init__, nlapt/diagnostics/__init__),
# self-registering LLM clients (nlapt.llm.base._ensure_builtin_registered),
# and lazily imported httpx / PIL.Image. Collect the first-party packages
# wholesale so no lazy module is ever missing from the bundle.
HIDDEN_IMPORTS = [
    *collect_submodules("nlapt"),
    *collect_submodules("nlapt_gui"),
    "httpx",
    "PIL.Image",
    # Florence-2 ONNX engine deps, imported lazily inside functions.
    # CPU EP only — GPU extras are pruned after Analysis (see _prune_analysis).
    "onnxruntime",
    "numpy",
]

# Modules that must never ship in the bundle.
# A global site-packages with torch / paddle / onnxruntime-gpu would otherwise
# be pulled in through onnxruntime.training / onnxruntime.transformers hooks
# and balloon a ~350 MB CPU build past 2 GB.
EXCLUDES = [
    "tests",
    "docs",
    "pytest",
    "pytest_qt",
    "PIL.ImageQt",  # optional Pillow-Qt shim pulls in extra Qt bindings
    "tkinter",
    "PyQt5",
    "PyQt6",
    "torch",
    "torchvision",
    "torchaudio",
    "paddle",
    "paddlex",
    "paddleocr",
    "bitsandbytes",
    "cv2",
    "scipy",
    "sklearn",
    "transformers",
    "tokenizers",
    "timm",
    "pandas",
    "matplotlib",
    "av",
    "altair",
    "hf_xet",
    "curl_cffi",
    "pytorch_lightning",
    "torchmetrics",
    "open_clip",
    "open_clip_torch",
    "onnxruntime.training",
    "onnxruntime.transformers",
]

# Drop leftover CUDA / GPU-provider binaries even when a GPU wheel is installed.
_DROP_BINARY_MARKERS = (
    "onnxruntime_providers_cuda",
    "onnxruntime_providers_tensorrt",
    "cublas",
    "cudnn",
    "cufft",
    "curand",
    "cusparse",
    "nvrtc",
    "cudart",
)
_DROP_DATA_PREFIXES = tuple(
    name + "/"
    for name in (
        "torch",
        "torchvision",
        "torchaudio",
        "paddle",
        "paddlex",
        "paddleocr",
        "bitsandbytes",
        "cv2",
        "scipy",
        "sklearn",
        "transformers",
        "tokenizers",
        "timm",
        "pandas",
        "matplotlib",
        "av",
        "altair",
        "hf_xet",
        "curl_cffi",
        "pytorch_lightning",
        "torchmetrics",
        "open_clip",
    )
)


def _toc_name(entry) -> str:
    name = entry[0] if isinstance(entry, (tuple, list)) else str(entry)
    return str(name).replace("\\", "/")


def _drop_binary(entry) -> bool:
    lowered = _toc_name(entry).lower()
    base = lowered.rsplit("/", 1)[-1]
    return any(marker in base for marker in _DROP_BINARY_MARKERS)


def _drop_data(entry) -> bool:
    lowered = _toc_name(entry).lower()
    if any(lowered.startswith(prefix) for prefix in _DROP_DATA_PREFIXES):
        return True
    return _drop_binary(entry)


def _prune_analysis(analysis) -> None:
    """Strip GPU/CUDA leftovers the onnxruntime hook may still collect."""
    analysis.binaries = [item for item in analysis.binaries if not _drop_binary(item)]
    analysis.datas = [item for item in analysis.datas if not _drop_data(item)]


a = Analysis(  # noqa: F821 - injected by PyInstaller
    [ENTRY_SCRIPT],
    pathex=[ROOT],
    binaries=[],
    # Ship the swappable icon so load_app_icon() finds it at runtime too.
    datas=[(ICON_FILE, "packaging")],
    hiddenimports=HIDDEN_IMPORTS,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=EXCLUDES,
    noarchive=False,
)
_prune_analysis(a)

pyz = PYZ(a.pure)  # noqa: F821 - injected by PyInstaller

exe = EXE(  # noqa: F821 - injected by PyInstaller
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name=APP_NAME,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,  # windowed app - no console window
    disable_windowed_traceback=False,
    icon=ICON_FILE,
)

coll = COLLECT(  # noqa: F821 - injected by PyInstaller
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name=APP_NAME,
)
